services:
  
  postgre-db-container:
    image: postgres:17.0
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: outwar-db
    ports:
      - "5432:5432"

  postgre-db-test:
    image: postgres:17.0
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: outwar-db-test
    ports:
      - "5433:5432"
  
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/redis.conf:/tmp/redis.conf
    command: [ "redis-server", "/tmp/redis.conf" ]
        
  backend:
    image: emirkovacevic/backend:latest
    build:
      context: .
      dockerfile: Outwar-regular-server/Dockerfile
    restart: always
    depends_on:
      - postgre-db-container
      - redis
    environment:
      - ASPNETCORE_URLS=http://+:11399
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "11399:11399"
        
  frontend:
    image: emirkovacevic/outwar-micro-x:latest
    restart: always
    ports:
      - "4201:80"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PRODUCTION: ${PRODUCTION}